config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :personens

  resources :bedrijfs

  resources :offertes

  resources :offerte_regels

  resources :prijs

  resources :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

end

app/models/prij.rb
class Prij < ActiveRecord::Base
end

app/models/prijs.rb
class Prijs < ActiveRecord::Base
  has_many :bedrijfs
end

app/controllers/prijs_controller.rb
class PrijsController < ApplicationController
  before_action :set_prij, only: [:show, :edit, :update, :destroy]

  # GET /prijs
  # GET /prijs.json
  def index
    @prijs = Prij.all
  end

  # GET /prijs/1
  # GET /prijs/1.json
  def show
  end

  # GET /prijs/new
  def new
    @prij = Prij.new
  end

  # GET /prijs/1/edit
  def edit
  end

  # POST /prijs
  # POST /prijs.json
  def create
    @prij = Prij.new(prij_params)

    respond_to do |format|
      if @prij.save
        format.html { redirect_to @prij, notice: 'Prij was successfully created.' }
        format.json { render :show, status: :created, location: @prij }
      else
        format.html { render :new }
        format.json { render json: @prij.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prijs/1
  # PATCH/PUT /prijs/1.json
  def update
    respond_to do |format|
      if @prij.update(prij_params)
        format.html { redirect_to @prij, notice: 'Prij was successfully updated.' }
        format.json { render :show, status: :ok, location: @prij }
      else
        format.html { render :edit }
        format.json { render json: @prij.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prijs/1
  # DELETE /prijs/1.json
  def destroy
    @prij.destroy
    respond_to do |format|
      format.html { redirect_to prijs_url, notice: 'Prij was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prij
      @prij = Prij.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prij_params
      params.require(:prij).permit(:product_nummer, :naam)
    end
end

app/helpers/prijs_helper.rb
module PrijsHelper
end

app/views/prijs/_form.html.erb
<%= form_for(@prij) do |f| %>
  <% if @prij.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prij.errors.count, "error") %> prohibited this prij from being saved:</h2>

      <ul>
      <% @prij.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_nummer %><br>
    <%= f.number_field :product_nummer %>
  </div>
  <div class="field">
    <%= f.label :naam %><br>
    <%= f.text_area :naam %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prijs/edit.html.erb
<h1>Editing prij</h1>

<%= render 'form' %>

<%= link_to 'Show', @prij %> |
<%= link_to 'Back', prijs_path %>

app/views/prijs/index.html.erb
<h1>Listing prijs</h1>

<table>
  <thead>
    <tr>
      <th>Product nummer</th>
      <th>Naam</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prijs.each do |prij| %>
      <tr>
        <td><%= prij.product_nummer %></td>
        <td><%= prij.naam %></td>
        <td><%= link_to 'Show', prij %></td>
        <td><%= link_to 'Edit', edit_prij_path(prij) %></td>
        <td><%= link_to 'Destroy', prij, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prij', new_prij_path %>

app/views/prijs/new.html.erb
<h1>New prij</h1>

<%= render 'form' %>

<%= link_to 'Back', prijs_path %>

app/views/prijs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product nummer:</strong>
  <%= @prij.product_nummer %>
</p>

<p>
  <strong>Naam:</strong>
  <%= @prij.naam %>
</p>

<%= link_to 'Edit', edit_prij_path(@prij) %> |
<%= link_to 'Back', prijs_path %>