config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :personens

  resources :bedrijfs

  resources :offertes

  resources :offerte_regels

  resources :prijs

  resources :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

end

app/models/offerte_regel.rb
class OfferteRegel < ActiveRecord::Base
  belongs_to :offerte
end

app/controllers/offerte_regels_controller.rb
class OfferteRegelsController < ApplicationController
  before_action :set_offerte_regel, only: [:show, :edit, :update, :destroy]

  # GET /offerte_regels
  # GET /offerte_regels.json
  def index
    @offerte_regels = OfferteRegel.all
  end

  # GET /offerte_regels/1
  # GET /offerte_regels/1.json
  def show
  end

  # GET /offerte_regels/new
  def new
    @offerte_regel = OfferteRegel.new
  end

  # GET /offerte_regels/1/edit
  def edit
  end

  # POST /offerte_regels
  # POST /offerte_regels.json
  def create
    @offerte_regel = OfferteRegel.new(offerte_regel_params)

    respond_to do |format|
      if @offerte_regel.save
        format.html { redirect_to @offerte_regel, notice: 'Offerte regel was successfully created.' }
        format.json { render :show, status: :created, location: @offerte_regel }
      else
        format.html { render :new }
        format.json { render json: @offerte_regel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offerte_regels/1
  # PATCH/PUT /offerte_regels/1.json
  def update
    respond_to do |format|
      if @offerte_regel.update(offerte_regel_params)
        format.html { redirect_to @offerte_regel, notice: 'Offerte regel was successfully updated.' }
        format.json { render :show, status: :ok, location: @offerte_regel }
      else
        format.html { render :edit }
        format.json { render json: @offerte_regel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offerte_regels/1
  # DELETE /offerte_regels/1.json
  def destroy
    @offerte_regel.destroy
    respond_to do |format|
      format.html { redirect_to offerte_regels_url, notice: 'Offerte regel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offerte_regel
      @offerte_regel = OfferteRegel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offerte_regel_params
      params.require(:offerte_regel).permit(:artikel, :omschrijving, :aantal, :prijs, :post, :offerte_id)
    end
end

app/helpers/offerte_regels_helper.rb
module OfferteRegelsHelper
end

app/views/offerte_regels/_form.html.erb
<%= form_for(@offerte_regel) do |f| %>
  <% if @offerte_regel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offerte_regel.errors.count, "error") %> prohibited this offerte_regel from being saved:</h2>

      <ul>
      <% @offerte_regel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :artikel %><br>
    <%= f.text_area :artikel %>
  </div>
  <div class="field">
    <%= f.label :omschrijving %><br>
    <%= f.text_area :omschrijving %>
  </div>
  <div class="field">
    <%= f.label :aantal %><br>
    <%= f.number_field :aantal %>
  </div>
  <div class="field">
    <%= f.label :prijs %><br>
    <%= f.text_area :prijs %>
  </div>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_area :post %>
  </div>
  <div class="field">
    <%= f.label :offerte_id %><br>
    <%= f.text_field :offerte_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offerte_regels/edit.html.erb
<h1>Editing offerte_regel</h1>

<%= render 'form' %>

<%= link_to 'Show', @offerte_regel %> |
<%= link_to 'Back', offerte_regels_path %>

app/views/offerte_regels/index.html.erb
<h1>Listing offerte_regels</h1>

<table>
  <thead>
    <tr>
      <th>Artikel</th>
      <th>Omschrijving</th>
      <th>Aantal</th>
      <th>Prijs</th>
      <th>Post</th>
      <th>Offerte</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offerte_regels.each do |offerte_regel| %>
      <tr>
        <td><%= offerte_regel.artikel %></td>
        <td><%= offerte_regel.omschrijving %></td>
        <td><%= offerte_regel.aantal %></td>
        <td><%= offerte_regel.prijs %></td>
        <td><%= offerte_regel.post %></td>
        <td><%= offerte_regel.offerte %></td>
        <td><%= link_to 'Show', offerte_regel %></td>
        <td><%= link_to 'Edit', edit_offerte_regel_path(offerte_regel) %></td>
        <td><%= link_to 'Destroy', offerte_regel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offerte regel', new_offerte_regel_path %>

app/views/offerte_regels/new.html.erb
<h1>New offerte_regel</h1>

<%= render 'form' %>

<%= link_to 'Back', offerte_regels_path %>

app/views/offerte_regels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artikel:</strong>
  <%= @offerte_regel.artikel %>
</p>

<p>
  <strong>Omschrijving:</strong>
  <%= @offerte_regel.omschrijving %>
</p>

<p>
  <strong>Aantal:</strong>
  <%= @offerte_regel.aantal %>
</p>

<p>
  <strong>Prijs:</strong>
  <%= @offerte_regel.prijs %>
</p>

<p>
  <strong>Post:</strong>
  <%= @offerte_regel.post %>
</p>

<p>
  <strong>Offerte:</strong>
  <%= @offerte_regel.offerte %>
</p>

<%= link_to 'Edit', edit_offerte_regel_path(@offerte_regel) %> |
<%= link_to 'Back', offerte_regels_path %>