config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :personens

  resources :bedrijfs

  resources :offertes

  resources :offerte_regels

  resources :prijs

  resources :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

end

app/models/personen.rb
class Personen < ActiveRecord::Base
  belongs_to :bedrijf
  validates_formatting_of :email, using: :email
end

app/controllers/personens_controller.rb
class PersonensController < ApplicationController
  before_action :set_personen, only: [:show, :edit, :update, :destroy]

  # GET /personens
  # GET /personens.json
  def index
    @personens = Personen.all
  end

  # GET /personens/1
  # GET /personens/1.json
  def show
  end

  # GET /personens/new
  def new
    @personen = Personen.new
  end

  # GET /personens/1/edit
  def edit
  end

  # POST /personens
  # POST /personens.json
  def create
    @personen = Personen.new(personen_params)

    respond_to do |format|
      if @personen.save
        format.html { redirect_to @personen, notice: 'Personen was successfully created.' }
        format.json { render :show, status: :created, location: @personen }
      else
        format.html { render :new }
        format.json { render json: @personen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personens/1
  # PATCH/PUT /personens/1.json
  def update
    respond_to do |format|
      if @personen.update(personen_params)
        format.html { redirect_to @personen, notice: 'Personen was successfully updated.' }
        format.json { render :show, status: :ok, location: @personen }
      else
        format.html { render :edit }
        format.json { render json: @personen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personens/1
  # DELETE /personens/1.json
  def destroy
    @personen.destroy
    respond_to do |format|
      format.html { redirect_to personens_url, notice: 'Personen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personen
      @personen = Personen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personen_params
      params.require(:personen).permit(:voornaam, :achternaam, :email, :telefoon, :mobiel, :tussenvoegsel, :type, :functie, :afdeling, :bedrijf_id)
    end
end

app/helpers/personens_helper.rb
module PersonensHelper
end

app/views/personens/_form.html.erb
<%= form_for(@personen) do |f| %>
  <% if @personen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personen.errors.count, "error") %> prohibited this personen from being saved:</h2>

      <ul>
      <% @personen.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :voornaam %><br>
    <%= f.text_area :voornaam %>
  </div>
  <div class="field">
    <%= f.label :achternaam %><br>
    <%= f.text_area :achternaam %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefoon %><br>
    <%= f.text_area :telefoon %>
  </div>
  <div class="field">
    <%= f.label :mobiel %><br>
    <%= f.text_area :mobiel %>
  </div>
  <div class="field">
    <%= f.label :tussenvoegsel %><br>
    <%= f.text_area :tussenvoegsel %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_area :type %>
  </div>
  <div class="field">
    <%= f.label :functie %><br>
    <%= f.text_area :functie %>
  </div>
  <div class="field">
    <%= f.label :afdeling %><br>
    <%= f.text_area :afdeling %>
  </div>
  <div class="field">
    <%= f.label :bedrijf_id %><br>
    <%= f.text_field :bedrijf_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personens/edit.html.erb
<h1>Editing personen</h1>

<%= render 'form' %>

<%= link_to 'Show', @personen %> |
<%= link_to 'Back', personens_path %>

app/views/personens/index.html.erb
<h1>Listing personens</h1>

<table>
  <thead>
    <tr>
      <th>Voornaam</th>
      <th>Achternaam</th>
      <th>Email</th>
      <th>Telefoon</th>
      <th>Mobiel</th>
      <th>Tussenvoegsel</th>
      <th>Type</th>
      <th>Functie</th>
      <th>Afdeling</th>
      <th>Bedrijf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personens.each do |personen| %>
      <tr>
        <td><%= personen.voornaam %></td>
        <td><%= personen.achternaam %></td>
        <td><%= personen.email %></td>
        <td><%= personen.telefoon %></td>
        <td><%= personen.mobiel %></td>
        <td><%= personen.tussenvoegsel %></td>
        <td><%= personen.type %></td>
        <td><%= personen.functie %></td>
        <td><%= personen.afdeling %></td>
        <td><%= personen.bedrijf %></td>
        <td><%= link_to 'Show', personen %></td>
        <td><%= link_to 'Edit', edit_personen_path(personen) %></td>
        <td><%= link_to 'Destroy', personen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personen', new_personen_path %>

app/views/personens/new.html.erb
<h1>New personen</h1>

<%= render 'form' %>

<%= link_to 'Back', personens_path %>

app/views/personens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Voornaam:</strong>
  <%= @personen.voornaam %>
</p>

<p>
  <strong>Achternaam:</strong>
  <%= @personen.achternaam %>
</p>

<p>
  <strong>Email:</strong>
  <%= @personen.email %>
</p>

<p>
  <strong>Telefoon:</strong>
  <%= @personen.telefoon %>
</p>

<p>
  <strong>Mobiel:</strong>
  <%= @personen.mobiel %>
</p>

<p>
  <strong>Tussenvoegsel:</strong>
  <%= @personen.tussenvoegsel %>
</p>

<p>
  <strong>Type:</strong>
  <%= @personen.type %>
</p>

<p>
  <strong>Functie:</strong>
  <%= @personen.functie %>
</p>

<p>
  <strong>Afdeling:</strong>
  <%= @personen.afdeling %>
</p>

<p>
  <strong>Bedrijf:</strong>
  <%= @personen.bedrijf %>
</p>

<%= link_to 'Edit', edit_personen_path(@personen) %> |
<%= link_to 'Back', personens_path %>