config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :personens

  resources :bedrijfs

  resources :offertes

  resources :offerte_regels

  resources :prijs

  resources :orders

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

end

app/models/bedrijf.rb
class Bedrijf < ActiveRecord::Base
  belongs_to :prijs
end

app/controllers/bedrijfs_controller.rb
class BedrijfsController < ApplicationController
  before_action :set_bedrijf, only: [:show, :edit, :update, :destroy]

  # GET /bedrijfs
  # GET /bedrijfs.json
  def index
    @bedrijfs = Bedrijf.all
  end

  # GET /bedrijfs/1
  # GET /bedrijfs/1.json
  def show
  end

  # GET /bedrijfs/new
  def new
    @bedrijf = Bedrijf.new
  end

  # GET /bedrijfs/1/edit
  def edit
  end

  # POST /bedrijfs
  # POST /bedrijfs.json
  def create
    @bedrijf = Bedrijf.new(bedrijf_params)

    respond_to do |format|
      if @bedrijf.save
        format.html { redirect_to @bedrijf, notice: 'Bedrijf was successfully created.' }
        format.json { render :show, status: :created, location: @bedrijf }
      else
        format.html { render :new }
        format.json { render json: @bedrijf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bedrijfs/1
  # PATCH/PUT /bedrijfs/1.json
  def update
    respond_to do |format|
      if @bedrijf.update(bedrijf_params)
        format.html { redirect_to @bedrijf, notice: 'Bedrijf was successfully updated.' }
        format.json { render :show, status: :ok, location: @bedrijf }
      else
        format.html { render :edit }
        format.json { render json: @bedrijf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bedrijfs/1
  # DELETE /bedrijfs/1.json
  def destroy
    @bedrijf.destroy
    respond_to do |format|
      format.html { redirect_to bedrijfs_url, notice: 'Bedrijf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bedrijf
      @bedrijf = Bedrijf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bedrijf_params
      params.require(:bedrijf).permit(:bedrijfs_naam, :kvk, :email, :website, :straat, :nummer, :postcode, :land, :plaats, :prijs_id)
    end
end

app/helpers/bedrijfs_helper.rb
module BedrijfsHelper
end

app/views/bedrijfs/_form.html.erb
<%= form_for(@bedrijf) do |f| %>
  <% if @bedrijf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bedrijf.errors.count, "error") %> prohibited this bedrijf from being saved:</h2>

      <ul>
      <% @bedrijf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bedrijfs_naam %><br>
    <%= f.text_area :bedrijfs_naam %>
  </div>
  <div class="field">
    <%= f.label :kvk %><br>
    <%= f.text_area :kvk %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </div>
  <div class="field">
    <%= f.label :straat %><br>
    <%= f.text_area :straat %>
  </div>
  <div class="field">
    <%= f.label :nummer %><br>
    <%= f.text_area :nummer %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_area :postcode %>
  </div>
  <div class="field">
    <%= f.label :land %><br>
    <%= f.text_area :land %>
  </div>
  <div class="field">
    <%= f.label :plaats %><br>
    <%= f.text_area :plaats %>
  </div>
  <div class="field">
    <%= f.label :prijs_id %><br>
    <%= f.text_field :prijs_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bedrijfs/edit.html.erb
<h1>Editing bedrijf</h1>

<%= render 'form' %>

<%= link_to 'Show', @bedrijf %> |
<%= link_to 'Back', bedrijfs_path %>

app/views/bedrijfs/index.html.erb
<h1>Listing bedrijfs</h1>

<table>
  <thead>
    <tr>
      <th>Bedrijfs naam</th>
      <th>Kvk</th>
      <th>Email</th>
      <th>Website</th>
      <th>Straat</th>
      <th>Nummer</th>
      <th>Postcode</th>
      <th>Land</th>
      <th>Plaats</th>
      <th>Prijs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bedrijfs.each do |bedrijf| %>
      <tr>
        <td><%= bedrijf.bedrijfs_naam %></td>
        <td><%= bedrijf.kvk %></td>
        <td><%= bedrijf.email %></td>
        <td><%= bedrijf.website %></td>
        <td><%= bedrijf.straat %></td>
        <td><%= bedrijf.nummer %></td>
        <td><%= bedrijf.postcode %></td>
        <td><%= bedrijf.land %></td>
        <td><%= bedrijf.plaats %></td>
        <td><%= bedrijf.prijs %></td>
        <td><%= link_to 'Show', bedrijf %></td>
        <td><%= link_to 'Edit', edit_bedrijf_path(bedrijf) %></td>
        <td><%= link_to 'Destroy', bedrijf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bedrijf', new_bedrijf_path %>

app/views/bedrijfs/new.html.erb
<h1>New bedrijf</h1>

<%= render 'form' %>

<%= link_to 'Back', bedrijfs_path %>

app/views/bedrijfs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bedrijfs naam:</strong>
  <%= @bedrijf.bedrijfs_naam %>
</p>

<p>
  <strong>Kvk:</strong>
  <%= @bedrijf.kvk %>
</p>

<p>
  <strong>Email:</strong>
  <%= @bedrijf.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @bedrijf.website %>
</p>

<p>
  <strong>Straat:</strong>
  <%= @bedrijf.straat %>
</p>

<p>
  <strong>Nummer:</strong>
  <%= @bedrijf.nummer %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @bedrijf.postcode %>
</p>

<p>
  <strong>Land:</strong>
  <%= @bedrijf.land %>
</p>

<p>
  <strong>Plaats:</strong>
  <%= @bedrijf.plaats %>
</p>

<p>
  <strong>Prijs:</strong>
  <%= @bedrijf.prijs %>
</p>

<%= link_to 'Edit', edit_bedrijf_path(@bedrijf) %> |
<%= link_to 'Back', bedrijfs_path %>